// <auto-generated />
using BitirmeProjesiDeneme2.Utility;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitirmeProjesiDeneme2.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20241020182100_miktarsil")]
    partial class miktarsil
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BitirmeProjesiDeneme2.Models.Malzeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Malzemeler");
                });

            modelBuilder.Entity("BitirmeProjesiDeneme2.Models.Tarif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Açıklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tarifler");
                });

            modelBuilder.Entity("BitirmeProjesiDeneme2.Models.TarifMalzeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MalzemeId")
                        .HasColumnType("int");

                    b.Property<int>("TarifId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MalzemeId");

                    b.HasIndex("TarifId");

                    b.ToTable("TarifMalzemeleri");
                });

            modelBuilder.Entity("BitirmeProjesiDeneme2.Models.TarifMalzeme", b =>
                {
                    b.HasOne("BitirmeProjesiDeneme2.Models.Malzeme", "Malzeme")
                        .WithMany("TarifMalzemeler")
                        .HasForeignKey("MalzemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitirmeProjesiDeneme2.Models.Tarif", "Tarif")
                        .WithMany("TarifMalzemeler")
                        .HasForeignKey("TarifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Malzeme");

                    b.Navigation("Tarif");
                });

            modelBuilder.Entity("BitirmeProjesiDeneme2.Models.Malzeme", b =>
                {
                    b.Navigation("TarifMalzemeler");
                });

            modelBuilder.Entity("BitirmeProjesiDeneme2.Models.Tarif", b =>
                {
                    b.Navigation("TarifMalzemeler");
                });
#pragma warning restore 612, 618
        }
    }
}
